<a href="https://colab.research.google.com/github/YG-0/Datascience_assisgnments/blob/main/Assignments_SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Salary Data SVM**

In [ ]:
# SVM Classification
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.preprocessing import StandardScaler

from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report


from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score



In [ ]:
df = pd.read_csv('SalaryData_Test(1).csv')

In [ ]:
df.head(10)

age          workclass      education  ...  hoursperweek          native  Salary
0   25            Private           11th  ...            40   United-States   <=50K
1   38            Private        HS-grad  ...            50   United-States   <=50K
2   28          Local-gov     Assoc-acdm  ...            40   United-States    >50K
3   44            Private   Some-college  ...            40   United-States    >50K
4   34            Private           10th  ...            30   United-States   <=50K
5   63   Self-emp-not-inc    Prof-school  ...            32   United-States    >50K
6   24            Private   Some-college  ...            40   United-States   <=50K
7   55            Private        7th-8th  ...            10   United-States   <=50K
8   65            Private        HS-grad  ...            40   United-States    >50K
9   36        Federal-gov      Bachelors  ...            40   United-States   <=50K

[10 rows x 14 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15060 entries, 0 to 15059
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            15060 non-null  int64 
 1   workclass      15060 non-null  object
 2   education      15060 non-null  object
 3   educationno    15060 non-null  int64 
 4   maritalstatus  15060 non-null  object
 5   occupation     15060 non-null  object
 6   relationship   15060 non-null  object
 7   race           15060 non-null  object
 8   sex            15060 non-null  object
 9   capitalgain    15060 non-null  int64 
 10  capitalloss    15060 non-null  int64 
 11  hoursperweek   15060 non-null  int64 
 12  native         15060 non-null  object
 13  Salary         15060 non-null  object
dtypes: int64(5), object(9)
memory usage: 1.6+ MB


In [ ]:
df.shape

(15060, 14)

In [ ]:
df1 = pd.read_csv("SalaryData_Train(1).csv")

In [ ]:
df1.head(10)

age          workclass   education  ...  hoursperweek          native  Salary
0   39          State-gov   Bachelors  ...            40   United-States   <=50K
1   50   Self-emp-not-inc   Bachelors  ...            13   United-States   <=50K
2   38            Private     HS-grad  ...            40   United-States   <=50K
3   53            Private        11th  ...            40   United-States   <=50K
4   28            Private   Bachelors  ...            40            Cuba   <=50K
5   37            Private     Masters  ...            40   United-States   <=50K
6   49            Private         9th  ...            16         Jamaica   <=50K
7   52   Self-emp-not-inc     HS-grad  ...            45   United-States    >50K
8   31            Private     Masters  ...            50   United-States    >50K
9   42            Private   Bachelors  ...            40   United-States    >50K

[10 rows x 14 columns]

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30161 entries, 0 to 30160
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            30161 non-null  int64 
 1   workclass      30161 non-null  object
 2   education      30161 non-null  object
 3   educationno    30161 non-null  int64 
 4   maritalstatus  30161 non-null  object
 5   occupation     30161 non-null  object
 6   relationship   30161 non-null  object
 7   race           30161 non-null  object
 8   sex            30161 non-null  object
 9   capitalgain    30161 non-null  int64 
 10  capitalloss    30161 non-null  int64 
 11  hoursperweek   30161 non-null  int64 
 12  native         30161 non-null  object
 13  Salary         30161 non-null  object
dtypes: int64(5), object(9)
memory usage: 3.2+ MB


In [ ]:
df1.shape

(30161, 14)

In [ ]:
df1.isnull().sum()

age              0
workclass        0
education        0
educationno      0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              0
capitalgain      0
capitalloss      0
hoursperweek     0
native           0
Salary           0
dtype: int64

In [ ]:
#columns
columns_names=["workclass","education","maritalstatus","occupation","relationship","race","sex","native","Salary"]

In [ ]:
from sklearn import preprocessing
number = preprocessing.LabelEncoder()
for i in columns_names:
    df[i] = number.fit_transform(df[i])
    df1[i] = number.fit_transform(df1[i])

colnames = df.columns

In [ ]:
df1.head()

age  workclass  education  ...  hoursperweek  native  Salary
0   39          5          9  ...            40      37       0
1   50          4          9  ...            13      37       0
2   38          2         11  ...            40      37       0
3   53          2          1  ...            40      37       0
4   28          2          9  ...            40       4       0

[5 rows x 14 columns]

In [ ]:
#Normalization of the data
from numpy import set_printoptions
from sklearn.preprocessing import MinMaxScaler

In [ ]:
def norm_func(i):
    x = ( i - i.min()) / ( i.max() - i.min())
    return(x)

In [ ]:
norm_data1 = norm_func(df.iloc[:,:])
norm_data1.head()

age  workclass  education  ...  hoursperweek    native  Salary
0  0.109589   0.333333   0.066667  ...      0.397959  0.948718     0.0
1  0.287671   0.333333   0.733333  ...      0.500000  0.948718     0.0
2  0.150685   0.166667   0.466667  ...      0.397959  0.948718     1.0
3  0.369863   0.333333   1.000000  ...      0.397959  0.948718     1.0
4  0.232877   0.333333   0.000000  ...      0.295918  0.948718     0.0

[5 rows x 14 columns]

In [ ]:
norm_data2= norm_func(df1.iloc[:,:])
norm_data2.head()

age  workclass  education  ...  hoursperweek    native  Salary
0  0.301370   0.833333   0.600000  ...      0.397959  0.948718     0.0
1  0.452055   0.666667   0.600000  ...      0.122449  0.948718     0.0
2  0.287671   0.333333   0.733333  ...      0.397959  0.948718     0.0
3  0.493151   0.333333   0.066667  ...      0.397959  0.948718     0.0
4  0.150685   0.333333   0.600000  ...      0.397959  0.102564     0.0

[5 rows x 14 columns]

In [ ]:
norm_data1.Salary.value_counts()

0.0    11360
1.0     3700
Name: Salary, dtype: int64

In [ ]:
norm_data2.Salary.value_counts()

0.0    22653
1.0     7508
Name: Salary, dtype: int64

In [ ]:
# class count
class_count_0, class_count_1 = norm_data1.Salary.value_counts()

In [ ]:
print(class_count_0,class_count_1)


11360 3700


In [ ]:
data_majority_train = norm_data1[norm_data1.Salary == 0.0]
data_minority_train = norm_data2[norm_data2.Salary == 1.0]

In [ ]:
train_major_count = class_count_0

In [ ]:
train_minor_count = class_count_1

In [ ]:
#class count
class_count_0, class_count_1 = norm_data1.Salary.value_counts()
print(class_count_0,class_count_1)

11360 3700


In [ ]:
test_major_count = class_count_0
test_minor_count = class_count_1

In [ ]:
data_majority_test = norm_data1[norm_data1.Salary == 0.0]
data_minority_test = norm_data1[norm_data1.Salary == 1.0]

In [ ]:
from sklearn.utils import resample
majority_downsamp_train = resample(data_majority_train, replace=False,
                                   n_samples=8000, random_state=123)

print(majority_downsamp_train.shape)

(8000, 14)


In [ ]:
data_down_sample_train = pd.concat([majority_downsamp_train,data_minority_train])

In [ ]:
print (data_down_sample_train.Salary.value_counts())

0.0    8000
1.0    7508
Name: Salary, dtype: int64


In [ ]:
majority_downsamp_test = resample(data_majority_test, replace=False,
                                   n_samples=4000, random_state=125)

In [ ]:
print (majority_downsamp_test.shape)

(4000, 14)


In [ ]:
data_down_sample_test = pd.concat([majority_downsamp_test,data_minority_test])
print (data_down_sample_test.Salary.value_counts())

0.0    4000
1.0    3700
Name: Salary, dtype: int64


In [ ]:
XTr = data_down_sample_train.drop(['Salary'],axis=1) 
YTr = data_down_sample_train['Salary']

In [ ]:
XTe = data_down_sample_test.drop(['Salary'],axis=1) 
YTe= data_down_sample_test['Salary']

In [ ]:
clf = SVC(C= 0.1,kernel='linear')
clf.fit(XTr , YTr)

SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
y_pred = clf.predict(XTe)
acc = accuracy_score(YTe, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(YTe, y_pred)

Accuracy = 75.57142857142857


array([[2890, 1110],
       [ 771, 2929]])

In [ ]:
y_pred

array([0., 0., 0., ..., 1., 1., 1.])

In [ ]:
clf = SVC(C= 0.1,kernel='poly')
clf.fit(XTr , YTr)
y_pred = clf.predict(XTe)
acc = accuracy_score(YTe, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(YTe, y_pred)

Accuracy = 80.75324675324676


array([[2991, 1009],
       [ 473, 3227]])

In [ ]:
y_pred

array([0., 0., 0., ..., 1., 1., 1.])

In [ ]:
clf = SVC(C= 0.1,kernel='rbf')
clf.fit(XTr , YTr)
y_pred = clf.predict(XTe)
acc = accuracy_score(YTe, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(YTe, y_pred)

Accuracy = 78.74025974025975


array([[2870, 1130],
       [ 507, 3193]])

In [ ]:
y_pred

array([0., 0., 0., ..., 1., 1., 1.])

In [ ]:
XTrain = norm_data2.iloc[:,0:13]
YTrain = norm_data2['Salary']

In [ ]:
XTest = norm_data1.iloc[:,0:13]
YTest = norm_data1['Salary']

In [ ]:
import imblearn
from imblearn.over_sampling import RandomOverSampler, SMOTE

/usr/local/lib/python3.7/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)


In [ ]:
smote = SMOTE(random_state=0)
X_smote_train, Y_smote_train = smote.fit_resample(XTrain, YTrain)
pd.Series(Y_smote_train).value_counts()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


1.0    22653
0.0    22653
dtype: int64

In [ ]:
print (pd.Series(Y_smote_train).value_counts())
XTrain = X_smote_train
YTrain = Y_smote_train

1.0    22653
0.0    22653
dtype: int64


In [ ]:
X_smote_test, Y_smote_test = smote.fit_resample(XTest, YTest)
pd.Series(Y_smote_test).value_counts()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


1.0    11360
0.0    11360
dtype: int64

In [ ]:
print (pd.Series(Y_smote_test).value_counts())
XTest = X_smote_test
YTest = Y_smote_test

1.0    11360
0.0    11360
dtype: int64


In [ ]:
clf = SVC(C= 0.1,kernel='linear')
clf.fit(XTrain , YTrain)
y_pred = clf.predict(XTest)
acc = accuracy_score(YTest, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(YTest, y_pred)

Accuracy = 75.95950704225352


array([[8270, 3090],
       [2372, 8988]])

In [ ]:
y_pred

array([0., 1., 1., ..., 0., 0., 1.])

In [ ]:
clf = SVC(C= 0.1,kernel='poly')
clf.fit(XTrain , YTrain)
y_pred = clf.predict(XTest)
acc = accuracy_score(YTest, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(YTest, y_pred)

Accuracy = 81.46126760563381


array([[8624, 2736],
       [1476, 9884]])

In [ ]:
y_pred

array([0., 1., 1., ..., 0., 0., 1.])

In [ ]:
clf = SVC(C= 0.1,kernel='rbf')
clf.fit(XTrain , YTrain)
from sklearn.metrics import accuracy_score, confusion_matrix
y_pred = clf.predict(XTest)
acc = accuracy_score(YTest, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(YTest, y_pred)

Accuracy = 80.29489436619718


array([[8350, 3010],
       [1467, 9893]])

In [ ]:
y_pred

array([0., 1., 1., ..., 0., 0., 1.])

# **Forest fires SVM**

In [ ]:
df = pd.read_csv("forestfires.csv")

In [ ]:
df.head()

month  day  FFMC   DMC  ...  monthnov  monthoct  monthsep  size_category
0   mar  fri  86.2  26.2  ...         0         0         0          small
1   oct  tue  90.6  35.4  ...         0         1         0          small
2   oct  sat  90.6  43.7  ...         0         1         0          small
3   mar  fri  91.7  33.3  ...         0         0         0          small
4   mar  sun  89.3  51.3  ...         0         0         0          small

[5 rows x 31 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 31 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   month          517 non-null    object 
 1   day            517 non-null    object 
 2   FFMC           517 non-null    float64
 3   DMC            517 non-null    float64
 4   DC             517 non-null    float64
 5   ISI            517 non-null    float64
 6   temp           517 non-null    float64
 7   RH             517 non-null    int64  
 8   wind           517 non-null    float64
 9   rain           517 non-null    float64
 10  area           517 non-null    float64
 11  dayfri         517 non-null    int64  
 12  daymon         517 non-null    int64  
 13  daysat         517 non-null    int64  
 14  daysun         517 non-null    int64  
 15  daythu         517 non-null    int64  
 16  daytue         517 non-null    int64  
 17  daywed         517 non-null    int64  
 18  monthapr  

In [ ]:
df.isnull().sum()

month            0
day              0
FFMC             0
DMC              0
DC               0
ISI              0
temp             0
RH               0
wind             0
rain             0
area             0
dayfri           0
daymon           0
daysat           0
daysun           0
daythu           0
daytue           0
daywed           0
monthapr         0
monthaug         0
monthdec         0
monthfeb         0
monthjan         0
monthjul         0
monthjun         0
monthmar         0
monthmay         0
monthnov         0
monthoct         0
monthsep         0
size_category    0
dtype: int64

In [ ]:
df = df.drop(['month'], axis=1)
df = df.drop(['day'], axis=1)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [ ]:
df['size_category'] = le.fit_transform(df['size_category'].astype(str))

In [ ]:
df.tail()

FFMC    DMC     DC   ISI  ...  monthnov  monthoct  monthsep  size_category
512  81.6   56.7  665.6   1.9  ...         0         0         0              0
513  81.6   56.7  665.6   1.9  ...         0         0         0              0
514  81.6   56.7  665.6   1.9  ...         0         0         0              0
515  94.4  146.0  614.7  11.3  ...         0         0         0              1
516  79.5    3.0  106.7   1.1  ...         1         0         0              1

[5 rows x 29 columns]

In [ ]:
X = df.iloc[:,0:28]

In [ ]:
X

FFMC    DMC     DC   ISI  ...  monthmay  monthnov  monthoct  monthsep
0    86.2   26.2   94.3   5.1  ...         0         0         0         0
1    90.6   35.4  669.1   6.7  ...         0         0         1         0
2    90.6   43.7  686.9   6.7  ...         0         0         1         0
3    91.7   33.3   77.5   9.0  ...         0         0         0         0
4    89.3   51.3  102.2   9.6  ...         0         0         0         0
..    ...    ...    ...   ...  ...       ...       ...       ...       ...
512  81.6   56.7  665.6   1.9  ...         0         0         0         0
513  81.6   56.7  665.6   1.9  ...         0         0         0         0
514  81.6   56.7  665.6   1.9  ...         0         0         0         0
515  94.4  146.0  614.7  11.3  ...         0         0         0         0
516  79.5    3.0  106.7   1.1  ...         0         1         0         0

[517 rows x 28 columns]

In [ ]:
y = df.iloc[:,28]

In [ ]:
y

0      1
1      1
2      1
3      1
4      1
      ..
512    0
513    0
514    0
515    1
516    1
Name: size_category, Length: 517, dtype: int64

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=101)

In [ ]:
model = SVC()

In [ ]:
model.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
predictions = model.predict(X_test)

In [ ]:
print(confusion_matrix(y_test,predictions))

[[  5  44]
 [  0 107]]


In [ ]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       1.00      0.10      0.19        49
           1       0.71      1.00      0.83       107

    accuracy                           0.72       156
   macro avg       0.85      0.55      0.51       156
weighted avg       0.80      0.72      0.63       156



Grid Search

In [ ]:
from sklearn.model_selection import GridSearchCV
clf = SVC()
param_grid = [{'kernel':['rbf','poly','linear'],'gamma':[100,50,10,0.5],'C':[10,0.1,15] }]
gsv = GridSearchCV(clf,param_grid,cv=10)
gsv.fit(X_train,y_train)

GridSearchCV(cv=10, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [10, 0.1, 15], 'gamma': [100, 50, 10, 0.5],
                          'kernel': ['rbf', 'poly', 'linear']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [ ]:
gsv.best_params_ , gsv.best_score_


({'C': 0.1, 'gamma': 100, 'kernel': 'linear'}, 0.9834084084084085)

In [ ]:
clf = SVC(C= 0.1,kernel='linear')
clf.fit(X_train , y_train)

SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix
y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)

Accuracy = 98.07692307692307


array([[ 49,   0],
       [  3, 104]])

In [ ]:
y_pred

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1])